version: "3.3"
services:
  frontend:
    image: 'angularapp'
    build:
      context: ./angularapp-buildoutput
    container_name: frontend
    ports:
      - '3001:9999'
    depends_on:
      - restapi
  
  restapi:
    image: 'restapi'
    build:
      context: ./restapi
    container_name: restapi
    ports:
      - '3000:3000'    